@startuml
allowmixing
skinparam linetype ortho

class DateiIO {
    lesenDatei()
    schreibenDatei()
    löschenDatei()
}

class LottoCLI {
   main()
}

class lottoschein{
    unglücksZahlen[]: int

    erstellenUnglückszahlen()
    löschenUnglückszahlen()
    ausgabeUnglückszahlen()
}

class lotto6aus49 extends lottoschein implements QuickTippGenerator{
    'man kann max 12 spielfelder erzeugen
    spielfeld[][49]: int
}

class eurojackpot extends lottoschein implements QuickTippGenerator{
    'man kann max 12 spielfelder erzeugen
    FünfAusFünfzigSpielfeld[][50]: int
    zweiAusZehnFeld[10]: int
    }


interface QuickTippGenerator{
    erzeugeTippreihe()
    ausgabeTippreihe()
}

file "Unglückszahlen.txt"

eurojackpot -[hidden]-> QuickTippGenerator
eurojackpot -[hidden]--> lottoschein
lottoschein "1" *-- "1" LottoCLI
lottoschein "1" *--- "1" DateiIO
DateiIO -- "Unglückszahlen.txt"
@enduml